#!/bin/bash

# Function to parse the app platform
parse_platform() {
    local platform=$1
    platform=$(echo "$platform" | tr '[:upper:]' '[:lower:]' | xargs)  # Convert to lowercase and strip spaces
    if [[ "$platform" == "android" || "$platform" == "and" || "$platform" == "a" ]]; then
        echo "android"
    elif [[ "$platform" == "ios" || "$platform" == "i" ]]; then
        echo "ios"
    elif [[ "$platform" == "styles" ]]; then 
        echo "styles"
    else
        echo "Invalid platform: Use one of 'android' or 'ios'"
        exit 1
    fi
}

# Parse the platform argument
platform=$(parse_platform "$1")

# Run command based on the platform
if [[ "$platform" == "android" ]]; then
    cargo tauri android build
elif [[ "$platform" == "ios" ]]; then
    cargo tauri ios build
else
    echo "Unsupported platform"
    exit 1
fi
