#!/bin/bash

export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
export ANDROID_HOME="$HOME/Library/Android/sdk"
# shellcheck disable=SC2155
# shellcheck disable=SC2086
export NDK_HOME="$ANDROID_HOME/ndk/$(ls -1 $ANDROID_HOME/ndk)"
export LEPTOS_TAILWIND_VERSION='v4.0.0'
export TAURI_DEV_HOST="192.168.0.170"

platform=$1
echo "parsing $platform..."
# Run command based on the platform
if [[ "$platform" == "android" ]]; then
    cargo tauri android dev
elif [[ "$platform" == "ios" ]]; then
    cargo tauri ios dev
elif [[ "$platform" == "styles" ]]; then
    npx @tailwindcss/cli -i ./app/styles/tailwind.css -o ./app/styles/app.css --watch --minify
elif [[ "$platform" == "server" ]]; then
    cd backend || exit
    air --root .
else
    echo "Unsupported platform"
    exit 1
fi
